/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ClientRouteImport } from './routes/client'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ClientIndexRouteImport } from './routes/client.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as ClientWishlistRouteImport } from './routes/client.wishlist'
import { Route as ClientTrackRouteImport } from './routes/client.track'
import { Route as ClientShopRouteImport } from './routes/client.shop'
import { Route as ClientCheckoutRouteImport } from './routes/client.checkout'
import { Route as ClientAccountRouteImport } from './routes/client.account'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminProductsRouteImport } from './routes/admin.products'
import { Route as AdminOrdersRouteImport } from './routes/admin.orders'
import { Route as AdminOffersRouteImport } from './routes/admin.offers'
import { Route as AdminCustomersRouteImport } from './routes/admin.customers'
import { Route as AdminContentRouteImport } from './routes/admin.content'
import { Route as ClientProductIdRouteImport } from './routes/client.product.$id'

const ClientRoute = ClientRouteImport.update({
  id: '/client',
  path: '/client',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientIndexRoute = ClientIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ClientRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientWishlistRoute = ClientWishlistRouteImport.update({
  id: '/wishlist',
  path: '/wishlist',
  getParentRoute: () => ClientRoute,
} as any)
const ClientTrackRoute = ClientTrackRouteImport.update({
  id: '/track',
  path: '/track',
  getParentRoute: () => ClientRoute,
} as any)
const ClientShopRoute = ClientShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => ClientRoute,
} as any)
const ClientCheckoutRoute = ClientCheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => ClientRoute,
} as any)
const ClientAccountRoute = ClientAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => ClientRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/admin/settings',
  path: '/admin/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminProductsRoute = AdminProductsRouteImport.update({
  id: '/admin/products',
  path: '/admin/products',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminOrdersRoute = AdminOrdersRouteImport.update({
  id: '/admin/orders',
  path: '/admin/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminOffersRoute = AdminOffersRouteImport.update({
  id: '/admin/offers',
  path: '/admin/offers',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCustomersRoute = AdminCustomersRouteImport.update({
  id: '/admin/customers',
  path: '/admin/customers',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminContentRoute = AdminContentRouteImport.update({
  id: '/admin/content',
  path: '/admin/content',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientProductIdRoute = ClientProductIdRouteImport.update({
  id: '/product/$id',
  path: '/product/$id',
  getParentRoute: () => ClientRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/client': typeof ClientRouteWithChildren
  '/admin/content': typeof AdminContentRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/offers': typeof AdminOffersRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/client/account': typeof ClientAccountRoute
  '/client/checkout': typeof ClientCheckoutRoute
  '/client/shop': typeof ClientShopRoute
  '/client/track': typeof ClientTrackRoute
  '/client/wishlist': typeof ClientWishlistRoute
  '/admin/': typeof AdminIndexRoute
  '/client/': typeof ClientIndexRoute
  '/client/product/$id': typeof ClientProductIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin/content': typeof AdminContentRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/offers': typeof AdminOffersRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/client/account': typeof ClientAccountRoute
  '/client/checkout': typeof ClientCheckoutRoute
  '/client/shop': typeof ClientShopRoute
  '/client/track': typeof ClientTrackRoute
  '/client/wishlist': typeof ClientWishlistRoute
  '/admin': typeof AdminIndexRoute
  '/client': typeof ClientIndexRoute
  '/client/product/$id': typeof ClientProductIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/client': typeof ClientRouteWithChildren
  '/admin/content': typeof AdminContentRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/offers': typeof AdminOffersRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/client/account': typeof ClientAccountRoute
  '/client/checkout': typeof ClientCheckoutRoute
  '/client/shop': typeof ClientShopRoute
  '/client/track': typeof ClientTrackRoute
  '/client/wishlist': typeof ClientWishlistRoute
  '/admin/': typeof AdminIndexRoute
  '/client/': typeof ClientIndexRoute
  '/client/product/$id': typeof ClientProductIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/client'
    | '/admin/content'
    | '/admin/customers'
    | '/admin/offers'
    | '/admin/orders'
    | '/admin/products'
    | '/admin/settings'
    | '/client/account'
    | '/client/checkout'
    | '/client/shop'
    | '/client/track'
    | '/client/wishlist'
    | '/admin/'
    | '/client/'
    | '/client/product/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin/content'
    | '/admin/customers'
    | '/admin/offers'
    | '/admin/orders'
    | '/admin/products'
    | '/admin/settings'
    | '/client/account'
    | '/client/checkout'
    | '/client/shop'
    | '/client/track'
    | '/client/wishlist'
    | '/admin'
    | '/client'
    | '/client/product/$id'
  id:
    | '__root__'
    | '/'
    | '/client'
    | '/admin/content'
    | '/admin/customers'
    | '/admin/offers'
    | '/admin/orders'
    | '/admin/products'
    | '/admin/settings'
    | '/client/account'
    | '/client/checkout'
    | '/client/shop'
    | '/client/track'
    | '/client/wishlist'
    | '/admin/'
    | '/client/'
    | '/client/product/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ClientRoute: typeof ClientRouteWithChildren
  AdminContentRoute: typeof AdminContentRoute
  AdminCustomersRoute: typeof AdminCustomersRoute
  AdminOffersRoute: typeof AdminOffersRoute
  AdminOrdersRoute: typeof AdminOrdersRoute
  AdminProductsRoute: typeof AdminProductsRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/client': {
      id: '/client'
      path: '/client'
      fullPath: '/client'
      preLoaderRoute: typeof ClientRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/client/': {
      id: '/client/'
      path: '/'
      fullPath: '/client/'
      preLoaderRoute: typeof ClientIndexRouteImport
      parentRoute: typeof ClientRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/client/wishlist': {
      id: '/client/wishlist'
      path: '/wishlist'
      fullPath: '/client/wishlist'
      preLoaderRoute: typeof ClientWishlistRouteImport
      parentRoute: typeof ClientRoute
    }
    '/client/track': {
      id: '/client/track'
      path: '/track'
      fullPath: '/client/track'
      preLoaderRoute: typeof ClientTrackRouteImport
      parentRoute: typeof ClientRoute
    }
    '/client/shop': {
      id: '/client/shop'
      path: '/shop'
      fullPath: '/client/shop'
      preLoaderRoute: typeof ClientShopRouteImport
      parentRoute: typeof ClientRoute
    }
    '/client/checkout': {
      id: '/client/checkout'
      path: '/checkout'
      fullPath: '/client/checkout'
      preLoaderRoute: typeof ClientCheckoutRouteImport
      parentRoute: typeof ClientRoute
    }
    '/client/account': {
      id: '/client/account'
      path: '/account'
      fullPath: '/client/account'
      preLoaderRoute: typeof ClientAccountRouteImport
      parentRoute: typeof ClientRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/admin/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/products': {
      id: '/admin/products'
      path: '/admin/products'
      fullPath: '/admin/products'
      preLoaderRoute: typeof AdminProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/orders': {
      id: '/admin/orders'
      path: '/admin/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AdminOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/offers': {
      id: '/admin/offers'
      path: '/admin/offers'
      fullPath: '/admin/offers'
      preLoaderRoute: typeof AdminOffersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/customers': {
      id: '/admin/customers'
      path: '/admin/customers'
      fullPath: '/admin/customers'
      preLoaderRoute: typeof AdminCustomersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/content': {
      id: '/admin/content'
      path: '/admin/content'
      fullPath: '/admin/content'
      preLoaderRoute: typeof AdminContentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/client/product/$id': {
      id: '/client/product/$id'
      path: '/product/$id'
      fullPath: '/client/product/$id'
      preLoaderRoute: typeof ClientProductIdRouteImport
      parentRoute: typeof ClientRoute
    }
  }
}

interface ClientRouteChildren {
  ClientAccountRoute: typeof ClientAccountRoute
  ClientCheckoutRoute: typeof ClientCheckoutRoute
  ClientShopRoute: typeof ClientShopRoute
  ClientTrackRoute: typeof ClientTrackRoute
  ClientWishlistRoute: typeof ClientWishlistRoute
  ClientIndexRoute: typeof ClientIndexRoute
  ClientProductIdRoute: typeof ClientProductIdRoute
}

const ClientRouteChildren: ClientRouteChildren = {
  ClientAccountRoute: ClientAccountRoute,
  ClientCheckoutRoute: ClientCheckoutRoute,
  ClientShopRoute: ClientShopRoute,
  ClientTrackRoute: ClientTrackRoute,
  ClientWishlistRoute: ClientWishlistRoute,
  ClientIndexRoute: ClientIndexRoute,
  ClientProductIdRoute: ClientProductIdRoute,
}

const ClientRouteWithChildren =
  ClientRoute._addFileChildren(ClientRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ClientRoute: ClientRouteWithChildren,
  AdminContentRoute: AdminContentRoute,
  AdminCustomersRoute: AdminCustomersRoute,
  AdminOffersRoute: AdminOffersRoute,
  AdminOrdersRoute: AdminOrdersRoute,
  AdminProductsRoute: AdminProductsRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminIndexRoute: AdminIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
